name: Deploy Storybook
# só executará o workflow quando tiver um push na branch main
on:
  push:
    branches:
      - main
# quando for pra produção, executará:
jobs:
  # nome do job
  build-and-deploy:
    runs-on: ubuntu-latest
    # comandos do deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # instala versão atualizada do código

      - name: Setup Node.js
        uses: actions/setup-node@v3 # instala o node
        with:
          node-version: 16

      - name: Install dependencies
      # instala dependencias de produção
        run: npm ci --legacy-peer-deps # ci -> definir ambiente não interativo

      - name: Build Storybook
        run: npm run build-storybook

      - name: Deploy Storybook
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}